---
title: "Problem_set_3" 
output: html_document
nombres: "Maria Jose Medellin 202122960, Juan Camilo Bejarano 202121927, Rafael Sanchez 202123676"
---


```{r, eval=F , echo=FALSE}
## Set-Up inicial
##Cargar los paquetes y librerías necesarias
rm(list=ls())
require(pacman)
p_load(tidyverse,rio,data.table)
```

# Punto 1
```{r, eval=T}
## Set.up inicial
rm(list=ls())

##Cargar los paquetes y librerías necesarias
require(pacman)
p_load(tidyverse,rio,data.table) 

## Punto 1.1

##Obtener la lista de archivos en input
rutas <- list.files("input" , recursive=T , full.names=T)

## Punto 1.2 

## Extraer las rutas
rutas_resto <- str_subset(string = rutas , pattern = "Resto - Ca")

## Cargar en lista
lista_resto <- import_list(file = rutas_resto)

## Textear la cadena de caracteres 
rutas_resto[1]
str_sub(rutas_resto[35],start = 14 , 17)

## Agregar ruta
View(lista_resto[[1]])
lista_resto[[1]]$path <- rutas_resto[1]

## Aplicar loop  
for (i in 1:length(lista_resto)){
  lista_resto[[i]]$path <- rutas_resto[i]  
  lista_resto[[i]]$year <- str_sub(lista_resto[[i]]$path,start = 14 , 17)
}
View(lista_resto[[20]])

## Punto 1.3

##Eliminar el elemento número 36 de la lista
lista_resto[[36]] <- NULL

# Combinar la lista en un solo data frame
df_resto <- rbindlist(l=lista_resto , use.names=T , fill=T)
```


#Punto 2
```{r,echo=F, eval=T}

##Importar archivo
db=import ("input/2019/Agosto.csv/Cabecera - Características generales (Personas).csv")

##Crear gráfico de dispersión con tema, título y nombre en los ejes
db %>%
  ggplot(aes(x = P6040, y = P6050)) +
  geom_point() +  # Add points
  labs(title = "Your Plot Title",      # Add a title
       x = "X-Axis Label",             # Label for the x-axis
       y = "Y-Axis Label") +          # Label for the y-axis
  theme_minimal()
```




