---
title: "Problem Set 3"
df_print: html_document
nombres: Maria Jose Medellin 202122960, Juan Camilo Bejarano 202121927, Rafael Sanchez
  202123676
R_ver: "R version 4.3.1 (2023-06-16 ucrt)"
---

### Configuración inicial
```{r, eval=T, message = F, warning=F}
## Set Up inicial
rm(list=ls())

##Cargar los paquetes y librerías necesarias
require(pacman)
p_load(tidyverse,rio,data.table,stringr,ggplot2)
```

# Punto 1
### 1.1
```{r, eval=T, message = F, warning=F}
##Obtener la lista de archivos en input
rutas <- list.files("input" , recursive=T , full.names=T)
```

### 1.2
```{r, eval=T, message = F, warning=F, error=F}
## Extraer las rutas
rutas_resto <- str_subset(string = rutas, pattern = "Resto - Ca")

## Cargar en lista
lista_resto <- vector("list", length = length(rutas_resto))

## Loop para cargar cada archivo
for (i in seq_along(rutas_resto)) {
  lista_resto[[i]] <- import(file = rutas_resto[i])
  lista_resto[[i]]$path <- rutas_resto[i]
  lista_resto[[i]]$year <- str_sub(rutas_resto[i], start = 7, end = 10)
}
```

### 1.3
```{r, eval=T, message = F, warning=F}
##Eliminar el elemento número 36 de la lista
lista_resto[[36]] <- NULL

# Combinar la lista en un solo data frame
df_resto <- rbindlist(l=lista_resto , use.names=T , fill=T)
```


# Punto 2
### Grafica 1
```{r,echo=F, eval=T, warning=F}
##Importar archivo
db=import ("input/2019/Agosto.csv/Cabecera - Características generales (Personas).csv")

##Crear gráfico de dispersión con tema, título y nombre en los ejes
db %>%
  ggplot(aes(x = P6040, y = ESC)) +
  geom_point() +  
  labs(title = "Gráfico de dispersión de años cumplidos y años de educación",      
       x = "Años cumplidos",             
       y = "Años de educación") +          
  theme_gray()
```


### Grafica 2
```{r,echo=F, eval=T, warning=F}
##Importar archivo
db=import ("input/2019/Agosto.csv/Cabecera - Características generales (Personas).csv")

##Crear gráfico de dispersión con tema, título y nombre en los ejes
db %>%
  ggplot(aes(x = P6040, y = ESC)) +
  geom_point() +  
  labs(title = "Gráfico de dispersión de años cumplidos y años de educación",      
       x = "Años cumplidos",             
       y = "Años de educación") +          
  theme_gray()
```

